### ISSUE TITLE
Lockfile doesn't include sub-dependencies

### ISSUE THREAD

**Issue by iamale** [pypa/pipfile#13]
Originally [reported by](https://gist.github.com/kennethreitz/4745d35e57108f5b766b8f6ff396de85#gistcomment-1927092) @charettes:

> Shouldn't implicit dependencies be included in the lock files as well à la `pip freeze`?

Reasoning for that is simple: imagine package A depends on `B == 1.0`, and package B depends on `C >= 1.0`. Then C 1.1 comes out with some subtle changes that break B completely, and — BAM! — your build is broken.

The problem with this is, PyPI doesn't return packages dependencies (I've tried several APIs, no luck), so in order to lock dependencies we need t actually install them first. Doesn't seem like a big deal to me, though.

**Comment by dstufft** [comment]
The lock file will contain the entire resolved dependency tree with specific pinned versions. The goal with it is to get the same basic workflow as (using your libraries above as an example):

```
# requirements.in
A==2.0
```

```console
$ virtualenv tmp
$ tmp/bin/pip install -r requirements.in
$ tmp/bin/pip freeze > requirements.txt
$ rm -rf tmp
```

Where in this example, ``requirements.in`` ~= ``Pipfile`` and ``requirements.txt`` ~= ``Pipfile.lock``.

**Comment by charettes** [comment]
@dstufft thanks for clarifying.
