### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by DiddiLeija** [pypa/pipfile#137]
Hello everyone,

I have noticed that many pypa repositories have changed its default branch to `main`. Can this project do the same?

**Comment by DiddiLeija** [comment]
Who has the rights to do this change? Maybe @di, @dstufft or @pradyunsg?

**Comment by DiddiLeija** [comment]
Is this possible?

**Comment by pradyunsg** [comment]
Done. I don't see any direct references that won't be automatically redirected.
