### ISSUE TITLE
Take inspiration from Yarn, Bundler and Cargo

### ISSUE THREAD

**Issue by sandstrom** [pypa/pipfile#25]
Perhaps you've already done this, but if not I'd suggest looking at how similar systems has solved issues around deterministic builds, dependency inconsistencies, the lock-file and similar. A non-exhaustive list:

- [Bundler](http://bundler.io/) (ruby)
- [Cargo](https://crates.io/) (rust)
- [Yarn](https://yarnpkg.com/) (node)
- [Composer](https://getcomposer.org/) (php)
- [CocoaPods](https://cocoapods.org/) (objective-c/swift)

If you have insights or tidbits from these projects, feel free to add them in the comments below.

**Comment by Incognito** [comment]
I suggest using composer from PHP as a model for idempotent builds as they're well past mature now and long since solved issues related to multiple origins, private origins, cross-package-conflicts, multiple source control methods (eg, you don't need to zip a package), etc...

**Comment by Incognito** [comment]
Ah also, they're one-level just like python deps. Things like node support recursive and shared top-level dependency.

**Comment by sandstrom** [comment]
@Incognito Good suggestion, I've added them to the list above.

**Comment by Profpatsch** [comment]
If you are searching for stable and mature, you should not forget [maven](https://maven.apache.org/).

**Comment by pkoch** [comment]
Consider directly involving the people to get lessons learnt and such. At least consulting with the likes of @wycats would be relevant.

**Comment by Incognito** [comment]
cc @seldaek or @naderman may have advice for you on this project.

**Comment by Seldaek** [comment]
If someone has specific questions I can try to give directions, but don't really have time atm to write an essay on all the things :)

**Comment by kennethreitz** [comment]
I have been having conversations with each of these communities (including Composer)—and much inspiration is being taken from each of these projects.

**Comment by kennethreitz** [comment]
Essays are not encouraged™

**Comment by simoncoulton** [comment]
I'd also take a look at Cocoapods (objective-c/swift), it's quite solid too.

**Comment by kennethreitz** [comment]
@simoncoulton thanks! If someone wants to have a video conversation with me who has experience with these tools, it would be much appreciated!

**Comment by kennethreitz** [comment]
Leaving this issue open for further comments, though it has already been well underway from the beginning ;)

**Comment by wycats** [comment]
@kennethreitz @sandstrom I can't promise to have a ton of time, but I'm generally happy to chat with people working on package manager stuffs :)

**Comment by ilessy** [comment]
[hex](https://hex.pm/)(elixir)

**Comment by kennethreitz** [comment]
Heavily inspired by all of these tools :)

**Comment by kennethreitz** [comment]
Composer, ironically, was where the most inspiration was taken for Pipenv. Good stuff.
