### ISSUE TITLE
Idea: using YAML instead of TOML

### ISSUE THREAD

**Issue by kirbyfan64** [pypa/pipfile#53]
Kind of like [shards does](https://github.com/crystal-lang/shards#usage). It's quite a bit more concise than TOML and even looks kind of Python-y.

I know the answer to this is probably going to be "big change, not enough gain", "conciseness isn't a good reason to switch", "harder to parse", etc...but I figured this still is worth a shot. ;)

**Comment by kennethreitz** [comment]
toml is being used by other packaging standards in python, so we're sticking to it.

**Comment by edmorley** [comment]
eg TOML was picked in PEP518 - see the discussion there for reasons:
https://www.python.org/dev/peps/pep-0518/#other-file-formats

**Comment by frob** [comment]
I don't see it argued anywhere that maybe using an unfinished standard, such as TOML, might pose a problem long term.

**Comment by thechief389** [comment]
I'd rather have it support both.
