### ISSUE TITLE
Is this project considers to be an official replacement for pip's requirements.txt?

### ISSUE THREAD

**Issue by jungornti** [pypa/pipfile#58]
Hello! Sorry for asking such a question as an issue, but search did not helped me about official position of this project.

Is this project considers to be an official replacement for pip's requirements.txt?

**Comment by jacebrowning** [comment]
Yes, check out the README: https://github.com/pypa/pipfile/blob/master/README.rst

**Comment by jungornti** [comment]
Thank you!
