### ISSUE TITLE
find's max_depth off by one?

### ISSUE THREAD

**Issue by spiliopoulos** [pypa/pipfile#65]
find with max_depth=1 will fail even if pipfile is in the current directory. Is that intentional?

**Comment by kennethreitz** [comment]
this code is being rewritten

**Comment by spiliopoulos** [comment]
Ok. I understand that. Will the api stay the same? Will there be a find after the rewrite is complete? If yes, will it have a max_depth parameter? If yes, what will be the semantics of that max_depth?

**Comment by kennethreitz** [comment]
who knows? that's entirely dependent upon https://github.com/pypa/pipfile/pull/57

**Comment by spiliopoulos** [comment]
Hmmm, that seems interesting. I do think this should be fixed for those who use the current version, but I'll close this for now.
