### ISSUE TITLE
How should Extra-index-url be treated in Pipfile?

### ISSUE THREAD

**Issue by arruda** [pypa/pipfile#68]
Will it be just another entry in `[[source]]` with a boolean `extra=True`?
Or pipfile will consider extra-index-url to be just like any other source? if so, anything that uses Pipfile will have to do some try/excepts to see if the current package is present in each of the listed sources (because some of them can be a extra, and contain just some specific listed packages)

**Comment by dstufft** [comment]
pip doesn't treat ``--extra-index-url`` differently from ``--index-url``, the only difference is ``--index-url`` overwrites the default and ``--extra-index-url`` adds an additional one, but beyond that they are exactly the same. So ``Pipfile`` will treat it just like any other source.

**Comment by arruda** [comment]
Thank @dstufft I was thinking in a solution to a problem in pipenv, but was unsure if this was going to be the correct behavior used in Pipfile. Thanks for the fast response :+1: :tada:
