### ISSUE TITLE
Outdated README example?

### ISSUE THREAD

**Issue by haochi** [pypa/pipfile#69]
In the README, the `develop` and `default` are both JSON arrays, but in the `Pipfile.lock` file in the `examples` folder, they are objects. e.g.

[README](https://github.com/pypa/pipfile/blob/036e3c7162b0a9742bd0bb719e36ef5d3834db30/README.rst#pipfilelock):
```json
    "development": [
        {"name": "nose", "version": "1.3.7", "hash": "..."},
    ]
```

[examples/Pipfile.lock](https://github.com/pypa/pipfile/blob/b05485daf7784b5b7df65828ae56cfedbd007996/examples/Pipfile.lock):
```
    "develop": {
        "nose": {
            "version": "==1.3.7",
            "hash": "sha256:dadcddc0aefbf99eea214e0f1232b94f2fa9bd98fa8353711dacb112bfcbbb2a"
        }
    }
```

Should it be assumed that the one `examples/Pipfile.lock` is the current spec since that's the generated format?

Also one is `development` and the other is `develop`.

**Comment by kennethreitz** [comment]
Let's take a look at what pipenv is doing and update the readme from there.

**Comment by kennethreitz** [comment]
Updated!

**Comment by kennethreitz** [comment]
Thanks @haochi
