### ISSUE TITLE
Consider indicating sub-dependencies in pipfile package list

### ISSUE THREAD

**Issue by elanorigby** [pypa/pipfile#76]
pipdeptree style

```
pipdeptree==0.10.1
  - pip [required: >=6.0.0, installed: 9.0.1]
Sphinx==1.6.2
  - alabaster [required: >=0.7,<0.8, installed: 0.7.10]
  - babel [required: !=2.0,>=1.3, installed: 2.4.0]
    - pytz [required: >=0a, installed: 2017.2]
  - docutils [required: >=0.11, installed: 0.13.1]
  - imagesize [required: Any, installed: 0.7.1]
  - Jinja2 [required: >=2.3, installed: 2.9.6]
    - MarkupSafe [required: >=0.23, installed: 1.0]
  - Pygments [required: >=2.0, installed: 2.2.0]
  - requests [required: >=2.0.0, installed: 2.17.3]
    - certifi [required: >=2017.4.17, installed: 2017.4.17]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.3]
    - idna [required: <2.6,>=2.5, installed: 2.5]
    - urllib3 [required: >=1.21.1,<1.22, installed: 1.21.1]
  - setuptools [required: Any, installed: 36.0.1]
  - six [required: >=1.5, installed: 1.10.0]
  - snowballstemmer [required: >=1.1, installed: 1.2.1]
  - sphinxcontrib-websupport [required: Any, installed: 1.0.1]
``` 

is more friendly and explicit than

```
alabaster = "==0.7.10"
Babel = "==2.4.0"
certifi = "==2017.4.17"
chardet = "==3.0.3"
docutils = "==0.13.1"
idna = "==2.5"
imagesize = "==0.7.1"
Jinja2 = "==2.9.6"
MarkupSafe = "==1.0"
pipdeptree = "==0.10.1"
Pygments = "==2.2.0"
pytz = "==2017.2"
requests = "==2.17.3"
snowballstemmer = "==1.2.1"
Sphinx = "==1.6.2"
sphinxcontrib-websupport = "==1.0.1"
urllib3 = "==1.21.1"
```

I'm not saying copy the syntax, just the idea of showing which package installed / is dependent upon which package. It is nice.

**Comment by elanorigby** [comment]
I would like to amend this to say that I got the above result in my pipfille from converting a requirements.txt. I have now started a new project with a fresh pipfile and only the very top level packages are listed (in this case it would be pipdeptree and Sphinx). So all is cool. I will leave this here in case it is useful to know that a requirements.txt file doesn't convert into a pipfile with just the very top packages. 

Possibly pipdeptree's method of figuring out dependencies can help with that?

**Comment by kennethreitz** [comment]
Does this belong in https://github.com/kennethreitz/pipenv instead?

**Comment by kennethreitz** [comment]
No, it does not. I see your point.

I think you're going to have to specify them at the top-level instead, or, ideally, leave them out.

**Comment by kennethreitz** [comment]
The whole idea of Pipfile is you can exclude sub-dependencies.
