### ISSUE TITLE
Why is Pipfile toml and other questions?

### ISSUE THREAD

**Issue by amjith** [pypa/pipfile#78]
I'm interested in this project. I'd like to understand the reasoning behind some of the design decisions. I had asked the following questions in the #pypa irc channel. But I figured this is an appropriate forum for them.

* Why is the Pipfile a `toml` file instead of a JSON?
* Since pipfile is inspired by yarn and cargo, is there a plan to support a more holistic approach to packaging? Such as `init`, `publish`, `test`, `run`, `build` etc?

**Comment by Screwtapello** [comment]
> Why is the Pipfile a TOML file

Because [other Python packaging standards](https://www.python.org/dev/peps/pep-0518/#other-file-formats) use TOML

**Comment by amjith** [comment]
Thank you for that. It makes perfect sense. 😄

**Comment by pradyunsg** [comment]
You can find the relevant discussions in #46, #14 and #10.
