### ISSUE TITLE
It will be very hard for tools (IDEs) to change dependencies programmically. 

### ISSUE THREAD

**Issue by defnull** [pypa/pipfile#8]
Tools and IDEs cannot edit the `Pipfile.lock` directly, because changes will be lost once the `Pipfile` is executed again. Parsing and editing `Pipfile` on the other hand is significantly more complicated that `requirements.txt`. IDEs will most likely not support `Pipfile` editing for a long time.

To put it in perspective: `Pipfile.lock` is a read-only approach. Developers are forced to manually edit the `Pipfile` with little to no tooling support in order do change the dependency settings of their project. This is a step backward compared to `requirements.txt` or other static file approaches.

**Comment by jayfk** [comment]
On top of that, please don't forget server side tools working with dependencies (pyup.io, requires.io, etc.). There's no way to support `Pipfile`s if they allow to run arbitrary Python code. Local developer tools might have a chance to establish a working solution over time, server side tools don't.

**Comment by pradyunsg** [comment]
I'd say, this is not relevant since #47.

**Comment by Phrohdoh** [comment]
Agreed that this isn't an issue (anymore?).

TOML is not difficult to parse and modify.
