### ISSUE TITLE
Why source is an array and why is it needed?

### ISSUE THREAD

**Issue by Woile** [pypa/pipfile#81]
Hi guys, I would like to understand why we are using this, and why source is an array:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
```
instead of something straightforwards like:
```
url = "https://pypi.python.org/simple"
verify_ssl = true
```

**Comment by kennethreitz** [comment]
you can have multiple sources.

**Comment by jacebrowning** [comment]
Could you provide an example of this? How is a source chosen from multiple sources?

**Comment by Screwtapello** [comment]
When working on a large project, you may need to fork some of your dependencies and add fixes faster than the official maintainers of those projects can merge those changes and make a new release. So, you might want an internal PyPI-like repository containing just your patched versions of packages, and also a reference to regular PyPI for all the packages you haven't patched yet. When looking for a package to install, Pip consults each source in order.
