### ISSUE TITLE
How to install from local folder?

### ISSUE THREAD

**Issue by wooyek** [pypa/pipfile#90]
We use internal proprietary libraries and we found that:

1. putting `--find-links=requirements/local` int `requirement.in`, 
2. listing  an unfreezed proprietary dependency in a `requirement.in`,
3. dropping a proper package version `whl` file in `requirements/local` project folder,
4. freezing versions in `requirements.txt` file just before release with `pip-compile`,
5. and shipping `requirements/local` folder contents to the server with project.

is the most easy solution for using private libraries. No need to setup private pypi server/source and use that securely.

When dependency has a newer version that we want we just drop this dependency `whl` file new version in the `requirements/local` and remove the old file. No need to update `requirements.in` by hand, update dependency path or whatever. This is also an easy update to be made by scripts, just delete old `requirements/local/dependency-*.whl` and put a new one, no need to parse and replace destination requirement files.

I was wondering how to recreate this with `Pipfile`. I was trying to do it with `[[source]]` but I'm not sure how to point to a project relative `requirements/local` folder in `url` attribute.

Is it doable? Can I somehow recreate `--find-links=requirements/local` effect in Pipfile?

**Comment by wooyek** [comment]
@kennethreitz would you like to commend on that?

**Comment by JosefAssad** [comment]
@wooyek this is probably too simplistic to be useful to you, but I think my use case is a subset of yours and I just `pipenv install file:///path/to/where/the/local/package/is`.

**Comment by wooyek** [comment]
Yes, it is.

Curently I can use relative path. It's imposible to use an absolute path that will work on any environment.

**Comment by geerk** [comment]
@wooyek Hi, so were you able to replicate `--find-links` feature from pip? Couldn't find anything in the docs.

**Comment by wooyek** [comment]
No I did not. I forgo the use of pipenv as it is still covering only the simple and naive use of [requirements files](https://pip.pypa.io/en/stable/user_guide/#requirements-files), `--find-links` is just one of many missing features, IMHO. 

I find that requirements files partitioned in dev/prod/whaetever used with with [referring](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format) + [pip-compile](https://github.com/jazzband/pip-tools) + [plain sort command](http://man7.org/linux/man-pages/man1/sort.1.html), does a better job with keeping requirements tidy than pipenv in current state does.

**Comment by damienrj** [comment]
This had been a deal breaker for me as well.

**Comment by AlecBenzer** [comment]
Another vote for needing this. Was hoping to use pipenv for a new project but looks I'm still stuck with manual use of virtualenv/requirements.txt.

I'd have thought that just having a second source like:

```toml
[[source]]
url = "file://./wheelhouse"
name = "wheelhouse"
```

where `./wheelhouse` is a directory like I'd pass to `pip --find-links`, but this didn't seem to work.

---

Note that, besides needing an absolute path, another problem with:

```bash
pipenv install file:///path/to/where/the/local/package/is
```

is that it forces all people working on your project to use the exact same wheel, which doesn't work for us, as we have several platform-specific wheels, where different people need to use different versions of them depending on their platform.

**Comment by gweconsulting** [comment]
Has this issue resolved? If it has, could someone share the solution? Thank you.

**Comment by markdfisher** [comment]
> Curently I can use relative path. It's imposible to use an absolute path that will work on any environment.

I realize this is a bit late, but what if when you needed the absolute path, you did something like:
`origDir=$(pwd)`
`cd ${relPath}`
`absPath=$(pwd)`
`cd ${origDir}`

**Comment by mconigliaro** [comment]
This worked for me:

    [packages]
    foo = {editable = true, path = "../foo"}

Note that you'll get a very misleading parse error unless your dependency contains a valid `setup.py`.

**Comment by w1tebear** [comment]
A problem I have with the 'editable = true' manner of dependency inclusion is that you end up with the entire project in your venv rather than just the package modules. This can include sometimes bulky documentation, tools, tests, git repo files, etc.. needed for development  - sometimes quite a bit larger than the packages themselves.....
