### ISSUE TITLE
editable line to use egg packagage

### ISSUE THREAD

**Issue by Stibbons** [pypa/pipfile#93]
Hello.

I would like to propose the following amendement for the equivalent of `pip install -e .`

Instead of:
```
"e1839a8" = {path = ".", editable = true}
```

I would like to have:
```
"mypackage" = {path = ".", editable = true}
```
This would allow to get directly the name of the egg I am working on only by reading the Pipfile

**Comment by Stibbons** [comment]
I am working on integrating pipfile parser to PBR for example, so that project that uses PBR and Pipfile can work together happily but this syntax modification is required in order to easily reconstruct the pip install line

**Comment by Stibbons** [comment]
not relevant, pip does not support egg name when installing from local path

**Comment by davilima6** [comment]
Where does this fixed hash e1839a8 come from? It doesn't seem to vary across projects (it's even in README).

It'd be much more logical/readable to use the name defined in setup.py, wouldn't it?

**Comment by kennethreitz** [comment]
it's a sha256 of '.'. pull requests accepted!

**Comment by kennethreitz** [comment]
you can change it to whatever you like. it's just a placeholder

**Comment by jacebrowning** [comment]
I have found that if I run `python setup.py develop` [first](https://github.com/jacebrowning/template-python-demo/blob/35ba0d72af47ec93ff6ecff11b8bca6a41c806f5/Makefile#L48-L49), I am able to use the actual package name in [the `Pipfile`](https://github.com/jacebrowning/template-python-demo/blob/35ba0d72af47ec93ff6ecff11b8bca6a41c806f5/Pipfile#L13).

It would be nice if the presence of `path = "."` invoked `setup.py` automatically.
