### ISSUE TITLE
Using pipfile from distutils

### ISSUE THREAD

**Issue by waghanza** [pypa/pipfile#97]
Hi,

I found this **awesome** project to clearly manage requirements for a `python` project.

The actual `requirements.txt` file could be used to give **requirements** to install on `setup.py`.

In my `setup.py` file, I am doing

~~~python
install_requires=open('requirements.txt').readlines()
~~~

I want to do this to manage my dependencies in one place.

However, with `pipenv` I have to do

~~~python
install_requires=toml.loads(open('Pipfile').read())['packages'].keys()
~~~

Which requires `toml` module to be installed.

Is there any workaround ?

Regards,

**Comment by kennethreitz** [comment]
this is not recommended.
